/**
 * 一次性导入名单脚本
 * 用法: node backend/scripts/import-roster.js
 */

const rosterService = require('../src/services/rosterService');

const entries = [
  { name: '舒梓萱', school: '谷山学校', grade: 6, class: 3 },
  { name: '王澳轩', school: '谷山学校', grade: 6, class: 3 },
  { name: '曾佳蔓', school: '谷山学校', grade: 7, class: 1 },
  { name: '钟文骏', school: '谷山学校', grade: 6, class: 3 },
  { name: '宋泇音', school: '中华路小学', grade: 7, class: 7 },
  { name: '李诗语', school: '中华路小学', grade: 7, class: 5 },
  { name: '王浩轩', school: '谷山学校', grade: 7, class: 3 },
  { name: '石浩燚', school: '谷山学校', grade: 7, class: 3 },
  { name: '唐瑞聪', school: '谷山学校', grade: 7, class: 3 },
  { name: '彭梓宸', school: '谷山学校', grade: 7, class: 3 },
  { name: '聂琪杨', school: '谷山学校', grade: 7, class: 1 },
  { name: '宋宇航', school: '谷山学校', grade: 7, class: 6 },
  { name: '张梓祺', school: '谷山学校', grade: 7, class: 6 },
  { name: '李明泽', school: '谷山学校', grade: 7, class: 6 },
  { name: '尚苏杭', school: '谷山学校', grade: 7, class: 6 },
  { name: '郑李玥', school: '谷山学校', grade: 7, class: 4 },
  { name: '赵曼合', school: '谷山学校', grade: 7, class: 5 },
  { name: '席榕君', school: '谷山学校', grade: 7, class: 5 },
  { name: '郑静怡', school: '谷山学校', grade: 7, class: 5 },
  { name: '胡可昕', school: '谷山学校', grade: 3, class: 3 },
  { name: '刘嘉源', school: '谷山学校', grade: 6, class: 2 },
  { name: '丰佳城1', school: '谷山学校', grade: 3, class: 3 },
  { name: '丰佳城', school: '谷山学校', grade: 3, class: 3 },
  { name: '周籽言1', school: '谷山学校', grade: 3, class: 3 },
  { name: '陈安琦', school: '谷山学校', grade: 4, class: 4 },
  { name: '彭玉瑶1', school: '谷山学校', grade: 3, class: 1 },
  { name: '肖如意', school: '谷山学校', grade: 4, class: 1 },
  { name: '范语璇', school: '谷山学校', grade: 7, class: 6 },
  { name: '赵致远', school: '谷山学校', grade: 7, class: 1 },
  { name: '黄皓昱', school: '谷山学校', grade: 6, class: 2 },
  { name: '赵军昊', school: '谷山学校', grade: 7, class: 2 },
  { name: '宋怡然', school: '谷山学校', grade: 7, class: 3 },
  { name: '任诗远', school: '谷山学校', grade: 7, class: 3 },
  { name: '赵婧悦', school: '谷山学校', grade: 7, class: 3 },
  { name: '程诗瑶', school: '谷山学校', grade: 7, class: 2 },
  { name: '刘笑帆', school: '谷山学校', grade: 7, class: 3 },
  { name: '李婉秋', school: '谷山学校', grade: 7, class: 3 },
  { name: '黄铭杨', school: '谷山学校', grade: 6, class: 1 },
  { name: '孔仕坤', school: '谷山学校', grade: 6, class: 1 },
  { name: '徐承睿', school: '谷山学校', grade: 6, class: 1 },
  { name: '吴恩泽', school: '谷山学校', grade: 6, class: 1 },
  { name: '郑清华', school: '谷山学校', grade: 6, class: 2 },
  { name: '周凤怡', school: '谷山学校', grade: 6, class: 2 },
  { name: '孙嘉美', school: '谷山学校', grade: 6, class: 2 },
  { name: '钟文俊', school: '谷山学校', grade: 6, class: 3 },
  { name: '廖泽熙', school: '谷山学校', grade: 6, class: 3 },
  { name: '冯广坤', school: '谷山学校', grade: 7, class: 1 },
  { name: '周梦洁', school: '谷山学校', grade: 7, class: 1 },
  { name: '余静涵', school: '谷山学校', grade: 7, class: 1 },
  { name: '丁乙丹', school: '谷山学校', grade: 7, class: 1 },
  { name: '李美君', school: '谷山学校', grade: 7, class: 1 },
  { name: '王宇帆', school: '谷山学校', grade: 7, class: 2 },
  { name: '钟雅文', school: '谷山学校', grade: 7, class: 2 },
  { name: '聂浩然', school: '谷山学校', grade: 7, class: 2 },
  { name: '章铭轩', school: '谷山学校', grade: 7, class: 3 },
  { name: '张梦泽', school: '谷山学校', grade: 7, class: 3 },
  { name: '刘笑帆', school: '谷山学校', grade: 7, class: 4 },
  { name: '杨梓豪', school: '谷山学校', grade: 7, class: 4 },
  { name: '赵海枫', school: '谷山学校', grade: 7, class: 4 },
  { name: '李文焱', school: '谷山学校', grade: 7, class: 5 },
  { name: '付嗣同', school: '谷山学校', grade: 7, class: 5 },
  { name: '郑李玥', school: '谷山学校', grade: 7, class: 5 },
  { name: '蔡丽珊', school: '谷山学校', grade: 7, class: 5 },
  { name: '李佳怡', school: '谷山学校', grade: 7, class: 6 },
  { name: '钟赟杰', school: '谷山学校', grade: 7, class: 6 },
  { name: '王凯瑞', school: '谷山学校', grade: 7, class: 6 },
  { name: '李斯涵', school: '谷山学校', grade: 7, class: 6 },
  { name: '曾庆玥', school: '谷山学校', grade: 7, class: 6 },
  { name: '宋文祥', school: '谷山学校', grade: 7, class: 6 },
  { name: '范昊轩', school: '谷山学校', grade: 7, class: 6 },
  { name: '李彦锦', school: '谷山学校', grade: 7, class: 6 },
  { name: '彭馨瑶', school: '谷山学校', grade: 7, class: 6 },
  { name: '李旻轩', school: '谷山学校', grade: 7, class: 7 },
  { name: '李梓玥', school: '谷山学校', grade: 7, class: 7 },
  { name: '宋宇航', school: '谷山学校', grade: 7, class: 7 },
  { name: '陈璟浩', school: '谷山学校', grade: 7, class: 7 },
  { name: '朱秋天', school: '谷山学校', grade: 7, class: 7 },
  { name: '宋泇音', school: '谷山学校', grade: 7, class: 7 },
  { name: '石铭玥', school: '谷山学校', grade: 7, class: 7 },
  { name: '黄诗涵', school: '谷山学校', grade: 7, class: 7 },
  { name: '王昕怡', school: '谷山学校', grade: 7, class: 7 },
  { name: '文志明', school: '谷山学校', grade: 7, class: 7 },
  { name: '席铭智', school: '谷山学校', grade: 7, class: 7 },
  { name: '李哲颖', school: '谷山学校', grade: 7, class: 7 },
  { name: '邱谦文', school: '谷山学校', grade: 7, class: 7 },
  { name: '石海新', school: '谷山学校', grade: 7, class: 7 },
  { name: '胡喻博', school: '谷山学校', grade: 4, class: 1 },
  { name: '邵鑫琳', school: '谷山学校', grade: 3, class: 1 },
  { name: '陈梓璇', school: '谷山学校', grade: 3, class: 1 },
  { name: '李睿雪', school: '谷山学校', grade: 3, class: 1 },
  { name: '彭玉瑶', school: '谷山学校', grade: 3, class: 1 },
  { name: '郑书洋', school: '谷山学校', grade: 3, class: 1 },
  { name: '江明宸', school: '谷山学校', grade: 3, class: 1 },
  { name: '周祥瑞', school: '谷山学校', grade: 3, class: 1 },
  { name: '张益谦', school: '谷山学校', grade: 3, class: 2 },
  { name: '程正宇', school: '谷山学校', grade: 3, class: 2 },
  { name: '鲍志豪', school: '谷山学校', grade: 3, class: 2 },
  { name: '司玉娢', school: '谷山学校', grade: 3, class: 2 },
  { name: '李佳珺', school: '谷山学校', grade: 3, class: 2 },
  { name: '杜依沫', school: '谷山学校', grade: 3, class: 2 },
  { name: '巩绪文', school: '谷山学校', grade: 3, class: 3 },
  { name: '吴泓成', school: '谷山学校', grade: 3, class: 3 },
  { name: '李若兮', school: '谷山学校', grade: 3, class: 3 },
  { name: '周籽言', school: '谷山学校', grade: 3, class: 3 },
  { name: '熊柏霖', school: '谷山学校', grade: 3, class: 3 },
  { name: '姜宇柯', school: '谷山学校', grade: 3, class: 3 },
  { name: '熊嘉瑞', school: '谷山学校', grade: 3, class: 3 },
  { name: '徐浩仁', school: '谷山学校', grade: 3, class: 4 },
  { name: '盘文慧', school: '谷山学校', grade: 3, class: 4 },
  { name: '徐文博', school: '谷山学校', grade: 3, class: 4 },
  { name: '肖雨婷', school: '谷山学校', grade: 3, class: 4 },
  { name: '韦宇航', school: '谷山学校', grade: 3, class: 4 },
  { name: '涂钧洋', school: '谷山学校', grade: 3, class: 4 },
  { name: '宋楚轩', school: '谷山学校', grade: 4, class: 1 },
  { name: '陈梓涵', school: '谷山学校', grade: 4, class: 1 },
  { name: '何远航', school: '谷山学校', grade: 4, class: 1 },
  { name: '王羿帆', school: '谷山学校', grade: 4, class: 1 },
  { name: '陈红军', school: '谷山学校', grade: 4, class: 2 },
  { name: '蔺子宸', school: '谷山学校', grade: 4, class: 2 },
  { name: '阮浩轩', school: '谷山学校', grade: 4, class: 2 },
  { name: '章梦媛', school: '谷山学校', grade: 4, class: 2 },
  { name: '卢昌盛', school: '谷山学校', grade: 4, class: 3 },
  { name: '胡广第', school: '谷山学校', grade: 4, class: 3 },
  { name: '王梓铭', school: '谷山学校', grade: 4, class: 3 },
  { name: '王俊杰', school: '谷山学校', grade: 4, class: 3 },
  { name: '马文杰', school: '谷山学校', grade: 4, class: 3 },
  { name: '杨沐恩', school: '谷山学校', grade: 4, class: 3 },
  { name: '阮敬洪', school: '谷山学校', grade: 4, class: 4 },
  { name: '潘金铎', school: '谷山学校', grade: 4, class: 4 },
  { name: '周嘉林', school: '谷山学校', grade: 4, class: 4 },
  { name: '王家盛', school: '谷山学校', grade: 4, class: 4 },
  { name: '崔风豪', school: '中华路小学', grade: 3, class: 2 },
  { name: '滕景一', school: '中华路小学', grade: 3, class: 2 },
  { name: '赵敬莞', school: '中华路小学', grade: 6, class: 2 },
  { name: '魏佳颖', school: '中华路小学', grade: 3, class: 1 },
  { name: '张君雅', school: '中华路小学', grade: 3, class: 1 },
  { name: '周雯', school: '中华路小学', grade: 3, class: 1 },
  { name: '何书涵', school: '中华路小学', grade: 3, class: 1 },
  { name: '鲁慧欣', school: '中华路小学', grade: 3, class: 1 },
  { name: '谢正杨', school: '中华路小学', grade: 3, class: 2 },
  { name: '万佳成', school: '中华路小学', grade: 3, class: 2 },
  { name: '张宇泽', school: '中华路小学', grade: 3, class: 2 },
  { name: '龚宸宇', school: '中华路小学', grade: 3, class: 2 },
  { name: '张峻杨', school: '中华路小学', grade: 3, class: 2 },
  { name: '周净好', school: '中华路小学', grade: 3, class: 3 },
  { name: '李浩然', school: '中华路小学', grade: 3, class: 3 },
  { name: '张城宇', school: '中华路小学', grade: 3, class: 3 },
  { name: '唐楚玥', school: '中华路小学', grade: 3, class: 3 },
  { name: '周琪涵', school: '中华路小学', grade: 3, class: 3 },
  { name: '程心怡', school: '中华路小学', grade: 5, class: 1 },
  { name: '赵善如', school: '中华路小学', grade: 5, class: 1 },
  { name: '冯语萱', school: '中华路小学', grade: 5, class: 1 },
  { name: '毕佳欣', school: '中华路小学', grade: 5, class: 1 },
  { name: '何天星', school: '中华路小学', grade: 5, class: 1 },
  { name: '吴艺冉', school: '中华路小学', grade: 5, class: 2 },
  { name: '谭晓苒', school: '中华路小学', grade: 5, class: 2 },
  { name: '夏于凡', school: '中华路小学', grade: 5, class: 2 },
  { name: '宋慧怡', school: '中华路小学', grade: 5, class: 2 },
  { name: '任子怡', school: '中华路小学', grade: 6, class: 1 },
  { name: '张玉龙', school: '中华路小学', grade: 6, class: 1 },
  { name: '尚厚材', school: '中华路小学', grade: 6, class: 1 },
  { name: '龚俊哲', school: '中华路小学', grade: 6, class: 1 },
  { name: '刘思雨', school: '中华路小学', grade: 6, class: 1 },
  { name: '陈沙蕊', school: '中华路小学', grade: 6, class: 2 },
  { name: '汤欣磊', school: '中华路小学', grade: 6, class: 2 },
  { name: '孙瑞燃', school: '中华路小学', grade: 6, class: 2 },
  { name: '陈登阳', school: '中华路小学', grade: 6, class: 2 },
  { name: '熊天成', school: '中华路小学', grade: 6, class: 2 },
];

async function main() {
  console.log(`准备导入 ${entries.length} 条名单记录...`);

  const result = await rosterService.importRoster(entries);

  console.log(`\n导入完成:`);
  console.log(`  新增: ${result.created} 人`);
  console.log(`  跳过(重复): ${result.skipped} 人`);
  console.log(`  失败: ${result.errors.length} 人`);

  if (result.errors.length > 0) {
    console.log('\n失败记录:');
    result.errors.forEach(e => console.log(`  - ${e}`));
  }

  console.log('\n成功导入学生列表:');
  result.users.forEach(u => {
    console.log(`  ${u.realName} → ${u.school} ${u.grade}年级${u.class}班`);
  });

  process.exit(0);
}

main().catch(err => {
  console.error('导入失败:', err);
  process.exit(1);
});
